version: '3'

services:
  mysql-db :
    build : ./Mysql/db/.
    command : --default-authentication-plugin=mysql_native_password
    ports : 
      - "3306:3306"
  solr-db:
    image: solr
    ports :
      - "8983:8983"
  es-db:
    image: elasticsearch:7.17.6
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  redis-server :
    image: redis
    ports:
      - "6379:6379"
  backend :
    build : ./Backend/.
    ports : 
      - "5000:5000"
    depends_on:
      - mysql-db
      - redis-server
    command: ["./wait-for-it/wait-for-it.sh","-t","30" ,"mysql-db:3306", "--", "node", "server.js"]
  frontend :
    build : ./Frontend/.
    ports :
      - "3000:3000"